{
 "title": "Kannel",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(bearerbox_up, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bearerbox_up{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bearerbox_uptime_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Box Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(bearerbox_box_connections{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "SMSC Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(bearerbox_smsc_connections{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "SMS Rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(bearerbox_sms_sent_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "sent"
    },
    {
     "expr": "irate(bearerbox_sms_received_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "SMS Queues",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "bearerbox_sms_sent_queued{instance=\"$instance\"}",
     "legendFormat": "sent"
    },
    {
     "expr": "bearerbox_sms_received_queued{instance=\"$instance\"}",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "DLR Rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(bearerbox_dlr_sent_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "sent"
    },
    {
     "expr": "irate(bearerbox_dlr_received_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "DLR Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "bearerbox_dlr_queued{instance=\"$instance\"}",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "SMS Storesize",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "bearerbox_sms_storesize{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Box Queue by type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (bearerbox_box_queue{instance=\"$instance\"})",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  { "title": "SMSC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "SMSC SMS Rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bearerbox_smsc_sent_sms_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "sent"
    },
    {
     "expr": "sum(rate(bearerbox_smsc_received_sms_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "SMSC DLR Rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bearerbox_smsc_sent_dlr_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "sent"
    },
    {
     "expr": "sum(irate(bearerbox_smsc_received_dlr_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "SMSC Queued Messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bearerbox_smsc_queued_messages{instance=\"$instance\"})",
     "legendFormat": "queued messages"
    }
   ]
  },
  {
   "title": "SMSC Failed Messages Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bearerbox_smsc_failed_messages_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "failed messages"
    }
   ]
  }
 ]
}