name: Docker Image CI

on:
  push:
    tags:
      - v*

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build image
      run: |
        # Get version from git reference
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        
        # Strip 'v' prefix from tag name
        VERSION=$(echo $VERSION | sed -e 's/^v//')
        
        docker build . --file Dockerfile --tag ${{ github.actor }}/kannel_exporter:$VERSION
        docker tag ${{ github.actor }}/kannel_exporter:$VERSION ${{ github.actor }}/kannel_exporter:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push
      run: docker push ${{ github.actor }}/kannel_exporter
